apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-socket-r2dbc
  labels:
    app: r-socket-r2dbc
spec:
  replicas: 1
  template:
    metadata:
      name: r-socket-r2dbc
      labels:
        app: r-socket-r2dbc
    spec:
      containers:
        - name: r-socket-r2dbc
          image: daggerok/reactive-spring-k8s-r-socket-r2dbc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              name: r2dbc
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: r2dbc
            periodSeconds: 2
            timeoutSeconds: 99
            failureThreshold: 3
            initialDelaySeconds: 1
          livenessProbe:
            tcpSocket:
              port: r2dbc
            periodSeconds: 5
            timeoutSeconds: 99
            failureThreshold: 6
            initialDelaySeconds: 4
      restartPolicy: Always
  selector:
    matchLabels:
      app: r-socket-r2dbc
---
apiVersion: v1
kind: Service
metadata:
  name: r-socket-r2dbc
spec:
  selector:
    app: r-socket-r2dbc
  ports:
    - port: 8001
      name: r2dbc
      protocol: TCP
      nodePort: 30001
      targetPort: 8001
  type: NodePort
